ecomadmin/urls.py
from django.urls import path

from ecomadmin.views import *

app_name = 'dashboard'
urlpatterns = [
    path('', AdminView.as_view(), name="admin_index"),

    # category CRD (Create, Read, Delete)
    path('insert/category', CategoryFormView.as_view(), name="category_form"),
    path('category', CategoryView.as_view(), name="category"),
    path('delete/category/<slug:slug>/', CategoryDeleteView.as_view(), name='delete_category'),

    # product RD (Read, Delete)
    path('product', ProductView.as_view(), name="product"),
    path('delete/product/<slug:slug>/', ProductDeleteView.as_view(), name='delete_product'),

    # # vendor RUD (Read, Update, Delete)
    path('vendor', VendorView.as_view(), name="vendor"),
    path('update/vendor/<int:pk>', VendorUpdateFormView.as_view(), name="vendor_update_form"),
    path('delete/vendor/<int:pk>/', VendorDeleteView.as_view(), name='delete_vendor'),

    # # vendor R (Read)
    path('customer', CustomerView.as_view(), name="customer"),

    # order RUD (Read, Update, Delete)
    path('order', OrderView.as_view(), name="order"),
    path('update/order/<int:pk>', OrderUpdateFormView.as_view(), name="order_update_form"),
    # path('delete/order/<slug:slug>/', OrderDeleteView.as_view(), name='delete_order'),

    # # tracking RUD (Read, Update, Delete)
    path('tracking', TrackingView.as_view(), name="tracking"),
    path('update/tracking/<int:pk>', TrackingUpdateFormView.as_view(), name="tracking_update_form"),
    # path('delete/tracking/<slug:slug>/', TrackingDeleteView.as_view(), name='delete_tracking'),

    # # transaction RD (Read, Delete)
    path('transaction', TransactionView.as_view(), name="transaction"),

    # banner CRD (Create, Read, Delete)
    path('insert/banner', BannerFormView.as_view(), name="banner_form"),
    path('banner', BannerView.as_view(), name="banner"),
    path('delete/banner/<int:pk>/', BannerDeleteView.as_view(), name='delete_banner'),

    # about CRU (Create, Read, Update)
    path('insert/about-us', AboutUsFormView.as_view(), name="about_us_form"),
    path('about-us/', AboutUsView.as_view(), name="about_us"),
    path('update/about-us/<int:pk>/', AboutUsUpdateFormView.as_view(), name='about_us_update_form'),
]

ecomadmin/templates/about_us.html
{% extends '_dashboard.html' %}
{% load static %}
{% block dashboard_content %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">CMS - About Us</h1>
            {#            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i#}
            {#                    class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>#}
        </div>

        <!-- Content Row -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Company Detail</h6>
                <span class="float-right">
                    {% if about %}
                        <a class="btn btn-info btn-sm" style="color: white"
                           href="{% url 'dashboard:about_us_update_form' about.id %}">
                                    <i class="fas fa-plus">
                                    </i>
                                    Update Detail
                                </a>
                    {% else %}
                        <a class="btn btn-info btn-sm" style="color: white"
                           href="{% url 'dashboard:about_us_form' %}">
                                    <i class="fas fa-plus">
                                    </i>
                                    Add Detail
                                </a>

                    {% endif %}
                </span>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <div><h5 class="text-dark font-weight-bold">Company Name</h5>{{ about.title }}</div>
                        <br>
                        <div><h5 class="text-dark font-weight-bold">Company Address</h5>{{ about.address }}<br></div>
                        <div><h5 class="text-dark font-weight-bold">Company Information</h5>{{ about.description }}
                        </div>
                        <br>
                        <div><h5 class="text-dark font-weight-bold">Phone Number</h5>{{ about.phoneNo }}</div>
                        <br>
                        {% if about.mobileNo %}
                            <div><h5 class="text-dark font-weight-bold">Mobile Number</h5>{{ about.mobileNo }}</div>
                            <br>{% endif %}
                    </div>
                    <div class="col-6">
                        <div>
                            <img src="{{ about.logo.url }}" height="100%" width="100%">
                        </div>
                        <div>{% if about.photo %}
                            <img src="{{ about.photo.url }}" height="100%" width="100%">
                        {% endif %}</div>
                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}
<script src="{% static 'dashboard/js/demo/datatables-demo.js' %}"></script>

ecomadmin/templates/banner.html
{% extends '_dashboard.html' %}
{% load static %}
{% block dashboard_content %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">CMS - Banner</h1>
            {#            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i#}
            {#                    class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>#}
        </div>

        <!-- Content Row -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Banner List</h6>
                <span class="float-right"><a class="btn btn-info btn-sm" style="color: white"
                                             href="{% url 'dashboard:banner_form' %}">
                                    <i class="fas fa-plus">
                                    </i>
                                    Add Banner
                                </a></span>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="example1" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Name</th>
                            <th>Caption</th>
                            <th>Weight</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for banner in banners %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ banner.title }}</td>
                                <td>{{ banner.caption }}</td>
                                <td>{{ banner.weight }}</td>
                                <td><img alt="{{ banner.title }}" src="{{ banner.image.url }}"
                                         class="rounded mx-auto d-block"
                                         height="50" width="100"></td>
                                <td><a class="btn btn-info btn-sm" style="color: white"
                                       data-toggle="modal"
                                       data-target="#banner{{ banner.id }}del">
                                    <i class="fas fa-trash-alt">
                                    </i>
                                    Delete
                                </a></td>
                            </tr>
                            <div id="banner{{ banner.id }}del" class="modal fade"
                                 role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" style="alignment: left">
                                                Delete {{ banner.title }}</h4>
                                            <button type="button" class="close" data-dismiss="modal">
                                                &times;
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure you want to delete
                                                "{{ banner.title }}"?</p>
                                            <img alt="{{ banner.title }}" src="{{ banner.image.url }}"
                                                 class="rounded mx-auto d-block"
                                                 height="100" width="100%">
                                            <div class="modal-del-fo">
                                                <form method="post"
                                                      action="{% url 'dashboard:delete_banner' banner.id %}">
                                                    {% csrf_token %}
                                                    <button value="Confirm" class="btn btn-info btn-sm">
                                                        Yes
                                                    </button>
                                                    <button class="btn btn-info btn-sm"
                                                            data-dismiss="modal">No
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
{% endblock %}
<script src="{% static 'dashboard/js/demo/datatables-demo.js' %}"></script>

ecomadmin/templates/category.html
{% extends '_dashboard.html' %}
{% load static %}
{% block dashboard_content %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Inventory - Category</h1>
            {#            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i#}
            {#                    class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>#}
        </div>

        <!-- Content Row -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Category List</h6>
                <span class="float-right"><a class="btn btn-info btn-sm" style="color: white"
                                             href="{% url 'dashboard:category_form' %}">
                                    <i class="fas fa-plus">
                                    </i>
                                    Add Category
                                </a></span>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="example1" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Name</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ category.title }}</td>
                                <td><a class="btn btn-info btn-sm" style="color: white"
                                       data-toggle="modal"
                                       data-target="#category{{ category.slug }}del">
                                    <i class="fas fa-trash-alt">
                                    </i>
                                    Delete
                                </a></td>
                            </tr>
                            <div id="category{{ category.slug }}del" class="modal fade"
                                 role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" style="alignment: left">
                                                Delete {{ category.title }}</h4>
                                            <button type="button" class="close" data-dismiss="modal">
                                                &times;
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure you want to delete
                                                "{{ category.title }}"?</p>
                                            <div class="modal-del-fo">
                                                <form method="post"
                                                      action="{% url 'dashboard:delete_category' category.slug %}">
                                                    {% csrf_token %}
                                                    <button value="Confirm" class="btn btn-info btn-sm">
                                                        Yes
                                                    </button>
                                                    <button class="btn btn-info btn-sm"
                                                            data-dismiss="modal">No
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
{% endblock %}
<script src="{% static 'dashboard/js/demo/datatables-demo.js' %}"></script>

ecomadmin/templates/transaction.html
{% extends '_dashboard.html' %}
{% block dashboard_content %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Transaction - Transactions</h1>
            {#            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i#}
            {#                    class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>#}
        </div>

        <!-- Content Row -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Vendor Wise Transaction</h6>

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Vendor</th>
                            <th>Total Amount (Rs.)</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for transaction,total in transaction_list.items %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ transaction }}</td>
                                <td>{% if total == None %}0{% else %}{{ total }}{% endif %}</td>
                            </tr>

                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

ecomadmin/templates/vendor.html
{% extends '_dashboard.html' %}
{% block dashboard_content %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Vendor & Customer - Vendors</h1>
            {#            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i#}
            {#                    class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>#}
        </div>

        <!-- Content Row -->

        {% if un_verified_vendors %}
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Un-Verified Vendor List</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Company Name</th>
                            <th>Address</th>
                            <th>Phone No.</th>
                            <th>Pan/Vat No.</th>
                            <th>User Name</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for uvendor in un_verified_vendors %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ uvendor.company_name }}</td>
                                <td>{{ uvendor.company_address }}</td>
                                <td>{{ uvendor.company_phone }}</td>
                                <td>{{ uvendor.pan_vat_no }}</td>
                                <td>{{ uvendor.vendor.username }}</td>
                                <td>{% if uvendor.verify_status %} Verified {% else %}Un-Verified{% endif %}</td>
                                <td><a class="btn btn-info btn-sm" style="color: white"
                                       data-toggle="modal"
                                       data-target="#category{{ uvendor.vendor }}del">
                                    <i class="fas fa-trash-alt">
                                    </i>
                                    Edit
                                </a></td>
                            </tr>
                            <div id="category{{ uvendor.vendor }}del" class="modal fade"
                                 role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" style="alignment: left">
                                                Verification For {{ uvendor.company_name }}</h4>
                                            <button type="button" class="close" data-dismiss="modal">
                                                &times;
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="modal-del-fo">
                                                <form method="post"
                                                      action="{% url 'dashboard:vendor_update_form' uvendor.id %}">
                                                    {% csrf_token %}
                                                    <div class="form-row">
                                                        <div class="col-8"><img alt="{{ uvendor.pan_vat_no }}"
                                                                                src="{{ uvendor.pan_vat_registered_document.url }}"
                                                                                class="rounded mx-auto d-block"
                                                                                height="100%" width="100%"></div>
                                                        <div class="col-4">Pan/Vat Number :<br>{{ uvendor.pan_vat_no }}</div>
                                                    </div>
                                                    <div class="form-row">
                                                        <label for="verify_status">Verification Status</label>
                                                        <input type="checkbox" class="form-control"
                                                               id="verify_status"
                                                               name="verify_status" {% if uvendor.verify_status %}
                                                               checked {% endif %}>
                                                    </div>
                                                    <button type="submit" class="btn btn-info btn-sm">
                                                        Update
                                                    </button>
                                                    <button class="btn btn-info btn-sm"
                                                            data-dismiss="modal">Cancel
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <hr>
        {% endif %}

        {% if verified_vendors %}
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Verified Vendor List</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Company Name</th>
                            <th>Address</th>
                            <th>Phone No.</th>
                            <th>Pan/Vat No.</th>
                            <th>User Name</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for vendor in verified_vendors %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ vendor.company_name }}</td>
                                <td>{{ vendor.company_address }}</td>
                                <td>{{ vendor.company_phone }}</td>
                                <td>{{ vendor.pan_vat_no }}</td>
                                <td>{{ vendor.vendor.username }}</td>
                                <td>{% if vendor.verify_status %} Verified {% else %}Un-Verified{% endif %}</td>
                                <td><a class="btn btn-info btn-sm" style="color: white"
                                       data-toggle="modal"
                                       data-target="#vendor{{ vendor.vendor }}update">
                                    <i class="fas fa-trash-alt">
                                    </i>
                                    Edit
                                </a>
                                    <a class="btn btn-info btn-sm" style="color: white"
                                       data-toggle="modal"
                                       data-target="#vendor{{ vendor.vendor }}del">
                                        <i class="fas fa-trash-alt">
                                        </i>
                                        Delete
                                    </a>
                                </td>
                            </tr>
                            <div id="vendor{{ vendor.vendor }}update" class="modal fade"
                                 role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" style="alignment: left">
                                                Verification For {{ vendor.company_name }}</h4>
                                            <button type="button" class="close" data-dismiss="modal">
                                                &times;
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="modal-del-fo">
                                                <form method="post"
                                                      action="{% url 'dashboard:vendor_update_form' vendor.id %}">
                                                    {% csrf_token %}
                                                    <div class="form-row">
                                                        <label for="verify_status">Verification Status</label>
                                                        <input type="checkbox" class="form-control"
                                                               id="verify_status"
                                                               name="verify_status" {% if vendor.verify_status %}
                                                               checked {% endif %}>
                                                    </div>
                                                    <button type="submit" class="btn btn-info btn-sm">
                                                        Update
                                                    </button>
                                                    <button class="btn btn-info btn-sm"
                                                            data-dismiss="modal">Cancel
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id="vendor{{ vendor.vendor }}del" class="modal fade"
                                 role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" style="alignment: left">
                                                Delete {{ vendor.company_name }}</h4>
                                            <button type="button" class="close" data-dismiss="modal">
                                                &times;
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure you want to delete
                                                "{{ vendor.company_name }}"?</p>
                                            <div class="modal-del-fo">
                                                <form method="post"
                                                      action="{% url 'dashboard:delete_vendor' vendor.id %}">
                                                    {% csrf_token %}
                                                    <button value="Confirm" class="btn btn-info btn-sm">
                                                        Yes
                                                    </button>
                                                    <button class="btn btn-info btn-sm"
                                                            data-dismiss="modal">No
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}